"""idempotency key and attempt timestamps

Revision ID: 5e133419c9ce
Revises: 39f2b19d8249
Create Date: 2026-03-03 15:52:45.181548

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e133419c9ce"
down_revision: Union[str, Sequence[str], None] = "39f2b19d8249"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_attempts",
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "job_attempts",
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "jobs", sa.Column("idempotency_key", sa.String(length=128), nullable=True)
    )
    op.create_index(
        "uq_jobs_idempotency_key",
        "jobs",
        ["idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "idempotency_key")
    op.drop_column("job_attempts", "finished_at")
    op.drop_column("job_attempts", "started_at")
    op.drop_index("uq_jobs_idempotency_key", table_name="jobs")
    # ### end Alembic commands ###
